//  !!!!
//  STUDENTS, DO NOT EDIT THIS FILE!
//  !!!!

#import "specialChapter.typ": *
#import "../acronymList.typ": acronyms

#let glossary() = {
set page(numbering: "1")
set heading(numbering: none)
show: specialChapter.with(chapterTitle: "Glossary",content: [

== List of acronyms
#let arr = ()
#for (key, value) in acronyms.pairs() {
  arr.push(key)
  arr.push(value)
}

#set table(
  columns: 2, 
  align: (left, left),
  stroke: none,
)

#show table.cell: it => {
  if it.x == 0  {
    set text(weight: "extrabold")
    strong(it)
  } else {
    it
  }
}

#table( 
   ..arr
)


== List of Symbols

])

  
}
